name: Versión de Rama David-t v1

on:
  push:
    branches:
      - main

jobs:
  merge-and-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Merge main into David-t
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout David-t
          git merge --strategy-option theirs main --no-edit

      - name: Reset current branch to the latest commit
        run: |
          git reset --hard HEAD

      - name: Extract last commit message
        id: get_commit_message
        run: |
          last_commit_message=$(git log -1 --pretty=%B)
          echo "commit_message=$last_commit_message" >> $GITHUB_ENV

      - name: Extract last version and bump it
        id: bump_version
        run: |
          # Extract version part from the commit message
          version=$(echo "${{ env.commit_message }}" | grep -o 'Versión [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+')
          if [ -z "$version" ]; then
            echo "No se encontró ninguna versión."
            exit 1
          fi
          # Extract the version numbers
          version_numbers=$(echo "$version" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+')
          IFS='.' read -r -a parts <<< "$version_numbers"
          parts[4]=$((parts[4]+1))
          new_version="${parts[0]}.${parts[1]}.${parts[2]}.${parts[3]}.${parts[4]}"
          echo "new_version=Versión $new_version (Unión de Ramas)" >> $GITHUB_ENV

      - name: Commit new version
        run: |
          git commit --allow-empty -m "${{ env.new_version }}"
          git push origin David-t
